---
title: "国際政治経済演習"
description: |
  早稲田大学政治経済学部（2019年度）
author:
  - name: 土井　翔平
    affiliation: 国立情報学研究所<br>早稲田大学
date: "`r Sys.Date()`"
site: radix::radix_website
---

## 授業概要

この授業では、計量的な政治分析を自ら行えるようになることを目標に、基礎的なデータ分析の知識とプログラミング技術を学びます。
具体的にはRとRStudioによるデータ分析、Rmarkdownによるレポートやスライドの作成、Gitによるバージョン管理、Githubによるウェブサイトの公開などの方法を身につけます。

- 日時
  - 曜日：毎週水曜日
  - 時間：6時限(18:00-19:30)
- 場所：早稲田大学3号館
- 連絡先：[shohei.doi0504@gmail.com](mailto:shohei.doi0504@gmail.com)
- オフィスアワー：応相談

## 授業計画と講義資料

### 第1回：導入

[スライド]()、[宿題]()、[解答]()

#### 参考資料

[RとRStudioの導入]()

[RmarkdownとLaTeXによるレポート、スライド作成]()

[Gitによるバージョン管理]()

[GithubとRmarkdownによるウェブサイト作成]()

## その他

### 参考書

特に教科書は指定せず、使用する講義資料はこのウェブサイトを通じて配布しますが、自習用にいくつかの参考文献を提示しておきます。

#### 因果推論

社会科学における因果推論（特に因果効果の推定）に関して数式がほとんど使われないもの。

#### データ分析

計量経済学や機械学習に関して数式を用いた理論的な説明をしているもの。

#### RとRStudio

RとRStudioの使い方を説明するもの。

### 成績評価

この授業の目的は自ら計量政治分析ができるようになることなので、授業への参加態度 (25%) 、毎週の課題の内容 (25%) および期末課題の内容 (50%) によって判断します。

### 履修要件

#### データ分析

特に履修要件は定めていませんが、計量的な政治分析がどのようなものかイメージを持っていると望ましいです。

#### 数学

数式を用いたデータ分析の手法に関する解説を行いますが、数学に関する前提知識はありません。

#### プログラミング

プログラミング経験は問いませんが、コンピュータの最低限の操作はできることが求められます。

### ソフトウェア

#### OS

この授業で使用するソフトウェアはいずれもWindows, Mac, Linuxで実行可能なものですが、講師はMacを使ったことがないのでトラブルに対応できない可能性があります。

ただし、一般的に言ってデータ分析を行うのであればOSはMacもしくはLinuxであることが望ましいです。
Windowsユーザーは仮想マシンあるいはデュアルブートによってLinux環境を構築するという選択肢もあります。

#### プログラミング言語

この授業ではRおよびRStudioを用いたデータ分析を行いますが、その他の言語（例えばPythonやJulia）の使用を妨げるものではありません。

### オフィスアワー

オフィスアワーは日時や場所を定めていないので、必要に応じて相談の上、決定します。
もちろん、メール等による質問、相談も随時受け付けています。
