project:
  type: website
  output-dir: docs

website:
  title: "Shohei Doi | 土井翔平"
  google-analytics: "G-LLFB8XFPX5"
  navbar: 
    search: false

format:
  html:
    theme:
      - materia
      - custom.scss
    include-in-header: font.html
    mainfont: Noto Sans JP, Helvetica Neue, Arial, Hiragino Kaku Gothic ProN, Hiragino Sans, BIZ UDPGothic, Meiryo, sans-serif
    link-external-newwindow: true
    toc: true
    toc-title: " "
    callout-appearance: simple

lang: ja
