---
format:
  pdf:
    documentclass: bxjsarticle
    classoption: xelatex,ja=standard
    papersize: a4paper
    fontfamily: noto
    mainfont: Noto Serif CJK JP Light
    linkcolor: NavyBlue
    citecolor: NavyBlue
    urlcolor: NavyBlue
---

# Shohei Doi | 土井翔平

\vspace{15mm}

## Contact Information

Graduate School of Law and Public Policy School, Hokkaido University\vspace{-4mm}

North 9, West 7, Kita-ku, Sapporo-shi\vspace{-4mm}

Hokkaido, 0600809, Japan

E-mail: <sdoi@juris.hokudai.ac.jp>\vspace{-4mm}

Website: <https://shohei-doi.github.io/>

## Current Position

2020--present
: Associate Professor
: Graduate School of Law and Public Policy School, Hokkaido University

2021--present
: Visiting Associate Professor
: Information and Society Research Division, National Institute of Informatics

2022--present
: Special Research Officer
: Policy Research Institute, Ministry of Finance, Japan

## Previous Position

2019--2021
: Project Researcher
: Information and Society Research Division, National Institute of Informatics

2020
: Postdoctoral Fellow (PD)
: Japan Society for the Promotion of Science (JSPS)
: School of Political Science and Economics, Waseda University

2015--2017
: Research Fellow (DC1)
: Japan Society for the Promotion of Science (JSPS)
: Graduate School of Law, Kyoto University

2016
: Visiting Student Research Collaborator (VSRC)
: Department of Politics, Princeton University

## Research Interests

International Relations, Game Theory, Data Science

## Education

2019
: Ph.D. in International Relations
: Graduate School of Law, Kyoto University

2015
: M.A. in International Relations
: Graduate School of Law, Kyoto University

2013
: B.A. in Law and Politics
: Faculty of Law, Kyoto University

## Publication

## Articles (reviewed)

1. Mizuno, Takayuki, Shohei Doi, and Shuhei Kurizaki. ["The flow of corporate control in the global ownership network."](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0290229) *Plos one* 18.8 (2023): e0290229.
1. Mizuno, Takayuki, Shohei Doi, Takahiro Tsuchiya, and Shuhei Kurizaki. ["Socially responsible investing through the equity funds in the global ownership network."](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0256160) *Plos one* 16.8 (2021): e0256160.
1. Doi, Shohei, Takayuki Mizuno, and Naoya Fujiwara. ["Estimation of socioeconomic attributes from location information."](https://link.springer.com/article/10.1007/s42001-020-00073-w) *Journal of Computational Social Science* 4 (2021): 187-205.
1. Mizuno, Takayuki, Shohei Doi, and Shuhei Kurizaki. ["The power of corporate control in the global ownership network."](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0237862) *Plos one* 15.8 (2020): e0237862.

## Articles (not reviewed)

1. Ono, Jumpei, and Shohei Doi. "Women, Peace and Security: Literature Review of Women and Intrastate Conflict" *Annals, Public Policy Studies* 17 (2023): 79-100.
    - [女性と平和, 安全保障: 女性と内戦に関する研究動向](https://eprints.lib.hokudai.ac.jp/dspace/handle/2115/89011)
1. Tsuchiya, Takahiro, Shohei Doi, Takayuki Mizuno, Shuhei Kurizaki. "Difficulty and Possibility of Global Governance for SDGs through ESG investing: Big Data Analysis of Ownership Network" *The Faculty of Economics and Business Administration Journal,Kyoto University of Advanced Science* 5 (2023): 1-17. (in Japanese)
    - [SDGsをめぐるESG投資を通じたグローバル・ガバナンスの可能性―ビッグデータを用いた株保有ネットワークの分析―](https://kyotogakuen.repo.nii.ac.jp/records/1511)
1. Doi, Shohei, et al. ["South Korea–Japan FCR crisis and public opinion: Gathering survey data in real-time crisis development."](https://www.taylorfrancis.com/chapters/edit/10.4324/9781003143536-2/south-korea%E2%80%93japan-fcr-crisis-public-opinion-shohei-doi-kazunori-inamasu-shoko-kohama-atsushi-tago) *Japanese Public Sentiment on South Korea* (2021): 18-31.
1. Nakayama, Yumi, and Shohei Doi. "Text Analysis of International Immigration Institution: Speech by Nordic Countries in UNHCR " *Methods of International Relations Research: Principles and Practices* (2021):  213-236. (in Japnese)
    - [国際難民制度のテキスト分析：UNHCRにおける北欧諸国の発言を事例に](https://www.utp.or.jp/book/b587759.html)
1. Suzuki, Motoshi, Keisuke Iida, and Shohei Doi. ["Analyzing International Developmental Loan Markets with Rival Lenders."](https://link.springer.com/chapter/10.1007/978-4-431-56466-9_10) *Games of Conflict and Cooperation in Asia* (2017): 227-248.

See [researchmap](https://researchmap.jp/doishohei) for other research activities, including grants, awards, and presentations.

## Professional Service

### Reviewer

Conflict Management and Peace Science, International Relations of the Asia‑Pacific

### Membership

Japan Association of International Relations, Japan Association for International Security, Information Processing Society of Japan, Japanese Society for Artificial Intel‑ligence

## teaching Experience

See [researchmap](https://researchmap.jp/doishohei) and [my syllabi and course materials](https://sdoi.notion.site/sdoi/8c0646a64bb343f7bb9c235143510e03).

## Miscellaneous

### Languages

Japanese (native), English (intermediate)

### PC skills

\LaTeX, R, Python (3.x), Stata, MATLAB, Mathematica, Linux (Ubuntu), HTML and CSS

\vspace{15mm}

Last Updated: \the\year/\the\month/\the\day