---
title: "RMarkdownとLaTeXの導入"
description: |
  RMarkdownとLaTeXの導入とレポートやスライド作成に関する説明です。
author:
  - name: 土井　翔平
    affiliation: 国立情報学研究所
date: 2019-3-11
output:
  distill::distill_article:
    self_contained: false
categories:
  - software
  - R
  - LaTeX
---

## RMarkdownの基本

RMarkdownとはRによる分析とその報告（レポートやスライド）作成を容易に行うものです。

##### 以下、読み飛ばしても構いません。

普段、慣れ親しんでいるOffice Wordは[WYSIWYG](https://ja.wikipedia.org/wiki/WYSIWYG) (what you see is what you get) と呼ばれるものです。
その名の通り、画面に映っているものがそのまま成果物として得ることができます。
そして直接その成果物をいじることができます。

一方で、[マークアップ言語](https://ja.wikipedia.org/wiki/%E3%83%9E%E3%83%BC%E3%82%AF%E3%82%A2%E3%83%83%E3%83%97%E8%A8%80%E8%AA%9E)では文章の内容と文章の見た目、構造を区別した上で、すべてテキストで指定します。
代表的なマークアップ言語にはHTMLやLaTeXがあります。

例えば、LaTeXにおいて節のタイトルは`\section{hoge}`と記述します。
この`\section{}`が節のタイトルという構造を明示的に示しています。
マークアップ言語の場合、作業しているファイルから何かしら一手間加えて成果物を作ります。

<aside>
  HTMLの場合はブラウザを通じてウェブサイトを可視化しますし、LaTeXの場合は組版することでpdfなどに変換します。
</aside>

そして、Markdownとは簡単にマークアップするための書き方で、そこにRを実行する機能を加えたものがRMarkdownになります。

<aside>
  ちなみにRMarkdownはバックグラウンドでpandocと呼ばれるソフトウェアを通じてドキュメントを生成しています。
</aside>

### RMarkdownを使ってみる

RStudioの左上にあるファイル新規作成するボタンを押し、その中の`R Markdown`を押します。

設定を行う画面が出ますので、とりあえず`Author`に適当な名前を入れて`OK`を押します。

サンプルファイルが出てきますので適当なフォルダに保存し、エディタ上部の`Knit`というボタンを押すか、ショートカット`Ctrl+Shift+K`を押してください。

初回は必要なパッケージをダウンロードした後にHTMLファイルが作成され、プレビューが表示されます。

### RMarkdown記法

### スライド

### ダッシュボード

## LaTeXの導入

RMarkdownからpdfファイルを生成するにはLaTeXを導入する必要があります。
LaTeXのインストールは[TeX Live](https://www.tug.org/texlive/)を用いるのが標準的ですが（Macの場合は[MacTeX](http://www.tug.org/mactex/)も人気です）、非常にデータ量が大きくダウンロードに時間がかかるという問題があります。

そこで、ここでは[TinyTeX](https://yihui.name/tinytex/)を用いた簡単なインストールの方法について説明します。

<aside>
  TeX Liveではパッケージを全てダウンロードするのに対して、TinyTeXでは必要最小限のものだけをダウンロードし、足りないものは後からダウンロードするという手順になります。
</aside>

### Tiny TeX

次のコードで`tinytex`とLaTeXをインストールします。

```{r, eval = FALSE, echo = TRUE}
install.packages('tinytex')
tinytex::install_tinytex()
```

インストール後、RMarkdownの新規ファイルを作成しますが、ここでpdfを選択しましょう。

あとは先ほどと同様に保存して`Knit`します。

### 日本語の使用

LaTeXにおいて日本語を使用する場合は一手間かかります。

##### 以下、読み飛ばしても構いません。

LaTeXでは組版エンジンがいくつかに派生しており、日本語を使用する場合に簡単なのは[u]pLaTeXを使うことです。

しかし、[u]pLaTeXはモダンなLaTeXエンジンとは言えません。
例えばRMarkdownでつかえるのはpdfLaTeX, XeLaTeX, LuaLaTeXの3つで、OverleafではこれにLaTeXを加えた4つだけです。

このうち、日本語を使用できるのはXeLaTeXとLuaLaTeXで、XeLaTeXの方が組版速度が早い（らしい）のでここではXeLaTeXを使います。

#### フォントのインストール

#### yamlヘッダーの編集

### Beamer

LaTeXではBeamerと呼ばれるドキュメントクラスによってスライドを作成することができます。