---
title: "国際政治経済学演習"
description: |
  早稲田大学政治経済学部の国際政治経済学演習（多湖淳）の2019年度授業ページです。
date: "`r Sys.Date()`"
author: 
  - name: "土井　翔平"
    affiliation: 国立情報学研究所
site: distill::distill_website
---

## 講義内容

講師は主に[シラバス](https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=110300Q614012019110300Q61411&pLng=jp)で掲げられている授業目標のうちのデータ入手・精製能力とデータ分析・報告能力に関するRとRStudioの使い方について主に担当します。

<aside>
  講義ページは随時アップデートするので最新版を確認してください。
</aside>

また、リクエストがあればLaTeXによるレポートとスライドの作成、Gitによるバージョン管理、GitHubによるウェブサイト作成についても講義できます。

## 講義資料

### 第1回　操作化とデータ収集

当面は

> Maoz, Z. (2004). Pacifism and fightaholism in international politics: A structural history of national and dyadic conflict, 1816–1992. International Studies Review, 6(4), 107-133.

をレプリケート（再現、追試）することを目標にします。

#### 内容

- Maoz (2004) における変数の操作化
- レプリケーションに必要なデータの収集
- RとRStudioの基本的な操作

<aside>
  Maoz (2004) のうち必要な箇所について読んできておいてください。
</aside>

#### 資料

スライド、ノート

- [RとRStudioの導入](../notes/posts/2019-03-12-r/index.html)
- [RMarkdownとLaTeXの導入](../notes/posts/2019-03-12-rmarkdown/index.html)

## 参考資料

特定の教科書を指定することはありませんが、参考となる書籍やウェブサイトを提示しておきます。
また、[シラバス](https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=110300Q614012019110300Q61411&pLng=jp)にも参考文献が挙げられています。

<aside>
  もちろん、リクエストも承っています。
</aside>

### Rの使い方

- R用検索エンジンの[seekR](http://seekr.jp/)
- オンラインでRStudioを使用できる[RStudio Cloud](https://rstudio.cloud/)
- 拓殖大学の浅野先生の2018年度の[計量政治学01](https://www.asanoucla.com/%E8%AC%9B%E7%BE%A9%E4%B8%80%E8%A6%A7/keiryo2017/)
- 高知工科大学の矢内先生の2018年度の[計量経済学](http://yukiyanai.github.io/jp/classes/econometrics1/contents/)と[計量経済学応用](http://yukiyanai.github.io/jp/classes/econometrics2/)
- tidyverseをはじめとするRのパッケージを解説している[Heavy Watal](https://heavywatal.github.io/)
- RStudioやtidyverseの[チートシート](https://www.rstudio.com/resources/cheatsheets/)
- 今井先生の[Quantitative Social Science: An Introduction](http://qss.princeton.press/)のコードをtidyverseに翻訳した[Quantatitive Social Science: The R Tidyverse Code](https://jrnold.github.io/qss-tidy/)

### データ分析

- ブラウン大学の統計学を視覚的に理解するための[Seeing Theory](https://seeing-theory.brown.edu/)
- さまざまな可視化の例が掲載されている[Visual Vocablary](https://public.tableau.com/ja-jp/s/gallery/visual-vocabulary)

### MarkdownやLaTeX

- オンラインでLaTeXを使用できる[Overleaf](https://rstudio.cloud/)

## 備考

### 連絡先

基本的にSlackによる連絡で対応しますが、[メール](mailto:shohei.doi0504@gmail.com)を送ってくださっても構いません。

オフィスアワーはありませんので適宜アポイントを取っていただければ直接相談にのります。

### 使用するOSについて

一般的に使用されているOS (operating system) にはWindows, Mac, Linuxがありますが、この授業ではいずれのOSでも使用できる（クロスプラットフォームな）ソフトウェア、プログラミング言語のみを使用します。

<aside>
  データ分析を本格的に行う場合はMacもしくはLinuxを使用したほうがよいでしょう。
</aside>

ただし、講師はLinux (Ubuntu) とWindowsしか使えない環境にいるので、講義資料はLinuxとWIndowsを念頭に作成します。
また、Macにおけるトラブルには対応できない可能性があります。

<aside>
  誰かMacを（貸して）ください……
</aside>

### 使用する言語について

この授業ではプログラミング言語としてRを、統合開発環境 (IDE) としてRStudioを使用しますが、その他の言語（例えばPythonやJulia）やIDEを使用することを妨げるものではありません。